import * as TActions from "@tenderly/actions-test";
import { expect } from "chai";

//Read IVAN_PK from .env file
import * as dotenv from "dotenv";
dotenv.config();

import { network } from "hardhat";


describe("ynETHx withdraw", () => {

  it("Withdraw using Ivan's wallet", async (done) => {
    const runtime = new TActions.TestRuntime();

    // Performing tests on a hardhat mainnet fork
    const hh_network = await network.connect("hardhatMainnet");
    
    if (!process.env.IVAN_PK) {
      throw new Error("Please set IVAN_PK in the .env file");
    }

    runtime.context.secrets.put(
      "IVAN_PK",
      process.env.IVAN_PK
    );

    // Populate runtime context with provider object generated by Hardhat
    runtime.context.storage.putJson("provider", hh_network.provider);

    // Invoke the mock action
    //runtime.execute(onPoolCreatedEventEmitted, txEventCreatePool);

  });

});